export const GET_USERS_ADMIN_REQUEST = 'GET_USERS_ADMIN_REQUEST'
export const GET_USERS_ADMIN_SUCCESS = 'GET_USERS_ADMIN_SUCCESS'
export const GET_USERS_ADMIN_ERROR   = 'GET_USERS_ADMIN_ERROR'  
export const GET_USERS_ADMIN_RESET   = 'GET_USERS_ADMIN_RESET'

export const GET_USER_ADMIN_REQUEST = 'GET_USER_ADMIN_REQUEST'
export const GET_USER_ADMIN_SUCCESS = 'GET_USER_ADMIN_SUCCESS'
export const GET_USER_ADMIN_ERROR   = 'GET_USER_ADMIN_ERROR'  
export const GET_USER_ADMIN_RESET   = 'GET_USER_ADMIN_RESET'

export const GET_EMPLOYEES_ADMIN_REQUEST = 'GET_EMPLOYEES_ADMIN_REQUEST'
export const GET_EMPLOYEES_ADMIN_SUCCESS = 'GET_EMPLOYEES_ADMIN_SUCCESS'
export const GET_EMPLOYEES_ADMIN_ERROR   = 'GET_EMPLOYEES_ADMIN_ERROR'  
export const GET_EMPLOYEES_ADMIN_RESET   = 'GET_EMPLOYEES_ADMIN_RESET'

export const GET_FEEDBACKS_ADMIN_REQUEST = 'GET_FEEDBACKS_ADMIN_REQUEST'
export const GET_FEEDBACKS_ADMIN_SUCCESS = 'GET_FEEDBACKS_ADMIN_SUCCESS'
export const GET_FEEDBACKS_ADMIN_ERROR   = 'GET_FEEDBACKS_ADMIN_ERROR'  
export const GET_FEEDBACKS_ADMIN_RESET   = 'GET_FEEDBACKS_ADMIN_RESET'

export const GET_EMPLOYEE_ADMIN_REQUEST = 'GET_EMPLOYEE_ADMIN_REQUEST'
export const GET_EMPLOYEE_ADMIN_SUCCESS = 'GET_EMPLOYEE_ADMIN_SUCCESS'
export const GET_EMPLOYEE_ADMIN_ERROR   = 'GET_EMPLOYEE_ADMIN_ERROR'  
export const GET_EMPLOYEE_ADMIN_RESET   = 'GET_EMPLOYEE_ADMIN_RESET'