export const CREATE_BOOKING_REQUEST = 'CREATE_BOOKING_REQUEST'
export const CREATE_BOOKING_SUCCESS = 'CREATE_BOOKING_SUCCESS'
export const CREATE_BOOKING_ERROR   = 'CREATE_BOOKING_ERROR'
export const CREATE_BOOKING_RESET   = 'CREATE_BOOKING_RESET'

export const DELETE_BOOKING_REQUEST = 'DELETE_BOOKING_REQUEST'
export const DELETE_BOOKING_SUCCESS = 'DELETE_BOOKING_SUCCESS'
export const DELETE_BOOKING_ERROR   = 'DELETE_BOOKING_ERROR'
export const DELETE_BOOKING_RESET   = 'DELETE_BOOKING_RESET'

export const LIST_MY_BOOKING_REQUEST = 'LIST_MY_BOOKING_REQUEST'
export const LIST_MY_BOOKING_SUCCESS = 'LIST_MY_BOOKING_SUCCESS'
export const LIST_MY_BOOKING_ERROR   = 'LIST_MY_BOOKING_ERROR'
export const LIST_MY_BOOKING_RESET   = 'LIST_MY_BOOKING_RESET'

export const LIST_BOOKING_REQUEST = 'LIST_BOOKING_REQUEST'
export const LIST_BOOKING_SUCCESS = 'LIST_BOOKING_SUCCESS'
export const LIST_BOOKING_ERROR   = 'LIST_BOOKING_ERROR'
export const LIST_BOOKING_RESET   = 'LIST_BOOKING_RESET'