export const GET_STAFF_TO_PAY_SUB_CASH_REQUEST = 'GET_STAFF_TO_PAY_SUB_CASH_REQUEST'
export const GET_STAFF_TO_PAY_SUB_CASH_SUCCESS = 'GET_STAFF_TO_PAY_SUB_CASH_SUCCESS'
export const GET_STAFF_TO_PAY_SUB_CASH_RESET = 'GET_STAFF_TO_PAY_SUB_CASH_RESET'
export const GET_STAFF_TO_PAY_SUB_CASH_ERROR = 'GET_STAFF_TO_PAY_SUB_CASH_ERROR'

export const COMPLETE_PAY_SUB_CASH_REQUEST = 'COMPLETE_PAY_SUB_CASH_REQUEST'
export const COMPLETE_PAY_SUB_CASH_SUCCESS = 'COMPLETE_PAY_SUB_CASH_SUCCESS'
export const COMPLETE_PAY_SUB_CASH_RESET   = 'COMPLETE_PAY_SUB_CASH_RESET'
export const COMPLETE_PAY_SUB_CASH_ERROR   = 'COMPLETE_PAY_SUB_CASH_ERROR'