export const SET_SELECTED_PLAN = 'SET_SELECTED_PLAN';
export const SET_MONTHS = 'SET_MONTHS';

export const SET_PHONE = 'SET_PHONE';
export const SET_CODE = 'SET_CODE';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_FIRSTNAME = 'SET_FIRSTNAME';
export const SET_LASTNAME = 'SET_LASTNAME';
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';

export const SET_STREET = 'SET_STREET';
export const SET_HOUSE = 'SET_HOUSE';
export const SET_CITY = 'SET_CITY';
export const SET_STATE = 'SET_STATE';
export const SET_PINCODE = 'SET_PINCODE';

export const CREATE_SUBSCRIPTION_REQUEST = 'CREATE_SUBSCRIPTION_REQUEST'
export const CREATE_SUBSCRIPTION_SUCCESS = 'CREATE_SUBSCRIPTION_SUCCESS'
export const CREATE_SUBSCRIPTION_ERROR   = 'CREATE_SUBSCRIPTION_ERROR'
export const CREATE_SUBSCRIPTION_RESET   = 'CREATE_SUBSCRIPTION_RESET'

export const GET_SUBSCRIPTION_REQUEST = 'GET_SUBSCRIPTION_REQUEST'
export const GET_SUBSCRIPTION_SUCCESS = 'GET_SUBSCRIPTION_SUCCESS'
export const GET_SUBSCRIPTION_ERROR   = 'GET_SUBSCRIPTION_ERROR'
export const GET_SUBSCRIPTION_RESET   = 'GET_SUBSCRIPTION_RESET'

export const GET_SUBSCRIPTION_PLAN_REQUEST = 'GET_SUBSCRIPTION_PLAN_REQUEST'
export const GET_SUBSCRIPTION_PLAN_SUCCESS = 'GET_SUBSCRIPTION_PLAN_SUCCESS'
export const GET_SUBSCRIPTION_PLAN_ERROR   = 'GET_SUBSCRIPTION_PLAN_ERROR'
export const GET_SUBSCRIPTION_PLAN_RESET   = 'GET_SUBSCRIPTION_PLAN_RESET'

export const CREATE_SUBSCRIPTION_PLANS_REQUEST = 'CREATE_SUBSCRIPTION_PLANS_REQUEST'
export const CREATE_SUBSCRIPTION_PLANS_SUCCESS = 'CREATE_SUBSCRIPTION_PLANS_SUCCESS'
export const CREATE_SUBSCRIPTION_PLANS_ERROR   = 'CREATE_SUBSCRIPTION_PLANS_ERROR'
export const CREATE_SUBSCRIPTION_PLANS_RESET   = 'CREATE_SUBSCRIPTION_PLANS_RESET'