export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_ERROR   = 'USER_LOGIN_ERROR';
export const USER_LOGIN_RESET   = 'USER_LOGIN_RESET';

export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_ERROR   = 'USER_REGISTER_ERROR';
export const USER_REGISTER_RESET   = 'USER_REGISTER_RESET';

export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_ERROR   = 'USER_DATA_ERROR';
export const USER_DATA_RESET   = 'USER_DATA_RESET';

export const CREATE_EMPLOYEE_SUCCESS = 'CREATE_EMPLOYEE_SUCCESS';
export const CREATE_EMPLOYEE_REQUEST = 'CREATE_EMPLOYEE_REQUEST';
export const CREATE_EMPLOYEE_ERROR   = 'CREATE_EMPLOYEE_ERROR';
export const CREATE_EMPLOYEE_RESET   = 'CREATE_EMPLOYEE_RESET';

export const GET_SERVICE_AVALABLE_SUCCESS = 'GET_SERVICE_AVALABLE_SUCCESS';
export const GET_SERVICE_AVALABLE_REQUEST = 'GET_SERVICE_AVALABLE_REQUEST';
export const GET_SERVICE_AVALABLE_ERROR   = 'GET_SERVICE_AVALABLE_ERROR';
export const GET_SERVICE_AVALABLE_RESET   = 'GET_SERVICE_AVALABLE_RESET';
